

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Use the specified Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Verify LambdaTest credentials
      - name: Verify LambdaTest Credentials
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: |
          if [[ -z "$LT_USERNAME" || -z "$LT_ACCESS_KEY" ]]; then
            echo "Error: LambdaTest credentials are missing."
            exit 1
          fi

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Start the LambdaTest Tunnel using the GitHub Action
      - name: Start LambdaTest Tunnel
        uses: LambdaTest/LambdaTest-tunnel-action@v2
        id: tunnel
        with:
          user: ${{ secrets.LT_USERNAME }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "CI_Tunnel" # Optional: Name the tunnel for better tracking

      # Step 6: Run your Karma tests on LambdaTest
      - name: Run Karma Tests
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: npm run karma

      # Step 7: Upload coverage reports (optional)
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
