name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # You can add more Node.js versions here if needed.
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up environment variables
        env:
          API_KEY: ${{ secrets.API_KEY }}
          NODE_ENV: production # You can also define non-sensitive variables here
        run: |
          echo "API_KEY=$API_KEY"
          echo "NODE_ENV=$NODE_ENV"

      - name: Verify LambdaTest Credentials
        env:
          LAMBDATEST_TEST_STRING: ${{secrets.LAMBDATEST_TEST_STRING}}
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: |
          echo "Username: $LT_USERNAME"
          echo "Access Key Length: ${#LT_ACCESS_KEY}"
          echo "Access key:: $LAMBDATEST_TEST_STRING" printing...

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Install LambdaTest Tunnel
        run: npm install @lambdatest/node-tunnel

      - name: Start LambdaTest Tunnel
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: |
          npm install @lambdatest/node-tunnel
          node start-tunnel.js

      - name: Wait for LambdaTest Tunnel
        run: sleep 5

      - name: Run Karma Tests on LambdaTest
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        run: npm run karma

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3

      - name: Run security audit
        run: npm audit
